#!/usr/bin/env python3
"""Regenerate js/mavlink/messages.js from pymavlink's common dialect.

    pip install pymavlink
    python3 tools/gen_mavlink.py > js/mavlink/messages.js
"""
from pymavlink.dialects.v20 import common as m

IDS = [0, 1, 2, 11, 20, 21, 22, 23, 24, 30, 31, 32, 33, 36, 39, 40, 42, 43, 44, 45, 46, 47,
       51, 65, 66, 69, 70, 73, 74, 76, 77, 87, 92, 93, 105, 107, 113, 115, 147, 242, 245, 253]
TYPES = {'uint8_t': 'u8', 'int8_t': 'i8', 'char': 'char', 'uint16_t': 'u16', 'int16_t': 'i16',
         'uint32_t': 'u32', 'int32_t': 'i32', 'float': 'f32', 'uint64_t': 'u64', 'int64_t': 'i64',
         'double': 'f64', 'uint8_t_mavlink_version': 'u8'}

print("// AUTO-GENERATED by tools/gen_mavlink.py from pymavlink (MAVLink v2 common dialect).")
print("// Fields are listed in wire order: [name, type, arrayLength].")
print("export const MESSAGES = {")
for i in IDS:
    c = m.mavlink_map[i]
    types = dict(zip(c.fieldnames, c.fieldtypes))
    fields = []
    for f, n in zip(c.ordered_fieldnames, c.array_lengths):
        fields.append('[%r, %r, %d]' % (f, TYPES[types[f]], n))
    print("  %d: { name: %r, crcExtra: %d, fields: [%s] }," % (i, c.msgname, c.crc_extra, ", ".join(fields)))
print("};")
print("export const IDS = Object.fromEntries(Object.entries(MESSAGES).map(([id, m]) => [m.name, Number(id)]));")
